Complete the help snippet

diff --git a/system/xbin/tsencfs b/system/xbin/tsencfs
--- a/system/xbin/tsencfs
+++ b/system/xbin/tsencfs
@@ -10,7 +10,7 @@ set -o pipefail
 # Check if run under root --------------------------------
 if ! ls /data > /dev/null 2> /dev/null; then
     echo "[!] ERROR"
-    echo "    ts-binds needs to be invoked"
+    echo "    ts-encfs needs to be invoked"
     echo "    from an elevated shell."
     echo "    Please run 'su' first."
     echo
@@ -27,18 +27,40 @@ sdname=$(grep -m 1 "/mnt/media_rw/" /proc/mounts | grep -m 1 -Eo "[0-9A-Z]{4}-[0
 sd=/mnt/runtime/default/$sdname
 folderlist=$datadir/cached-folderlist.sh
 folderlistuser=$intraw/ts-encfs-folderlist.txt
+password=
 
 supass() {
-    /sbin/su -M -c "$@"
+    /sbin/su -M -c "$*"
 }
 
 printhelp() {
-    echo "tsencfs [options] [arg]"
+    echo "tsencfs [options] ([arg] [arg2])"
     echo
     echo "Available options:"
     echo
-    echo "help ............... Show this reference text"
-    echo "h | --help | -h .... Ditto"
+    echo "(help | h | --help | -h)"
+    echo "      Show this reference text"
+    echo "-x   [pair name]"
+    echo "      Mounts the pair as configured"
+    echo "      in the folderlist"
+    echo "-xo  [enc] [dec]"
+    echo "      Mounts the defined encrypted"
+    echo "      directory to another path. [enc] is encrypted"
+    echo "      directory while [dec] is the path to mount to"
+    echo "-xx  [pair name] [arg]...[argN]"
+    echo "      Same as -x but extraneous arguments are passed"
+    echo "      to encfs which would again passed to FUSE"
+    echo "-xox [enc] [dec] [arg]...[argN]"
+    echo "      Same as -xo but extraneous arguments are passed"
+    echo "      to encfs which would again passed to FUSE"
+    echo "-u   [pair name]"
+    echo "      Unmounts the pair as configured"
+    echo "      in the folderlist"
+    echo "-uo  [dec]"
+    echo "      Unmounts the defined path"
+    echo
+    echo "Warning: tsencfs is just a script."
+    echo "It cannot parse multiple \"switches\" at once"
 }
 
 # No action given ----------------------------------------
@@ -53,7 +75,39 @@ elif [ "$1" = "help" ] || [ "$1" = "h" ] || [ "$1" = "--help" ] || [ "$1" = "-h"
 
 # Mount --------------------------------------------------
 elif [ "$1" = "mount" ]; then
-
+    folderbind() {
+        if supass mountpoint -q \""$3"\"; then
+            echo "$1 is already mounted"
+        elif [ ! -d "$2" ]; then
+            echo "Mount aborted: Directory '$2' as source doesn't exist!"
+            exit 1
+        else
+            echo "Mounting $1"
+            if { supass echo \""$4"\" | encfs -S --public \""$2"\" \""$3"\" }; then
+                if { echo "$3" | grep -q "$sd"; }; then
+                    sdraw="$(echo "$3" | sed 's/\/mnt\/runtime\/default/\/mnt\/media_rw/g')"
+                    { supass encfs -S --public \""$2"\" \""$3"\"; } || exit 1
+                fi
+                echo "Bind successful"
+            else
+                echo "Bind failed"
+                exit 1
+            fi
+        fi
+    }
+    if [ ! "$2" ]; then
+        echo 'E: Bind name is not provided!'
+    elif [ "$2" = "all" ]; then
+        echo "Binding all entries"
+        . $folderlist
+        echo "All entries were processed"
+    elif [ "$2" = "o" ]; then
+        folderbind "o" "$3" "$4"
+    elif line="$(grep -m 1 "$2" $folderlist)"; then
+        eval "$line"
+    else
+        echo "Unable to bind $2, entry not found in list!"
+    fi
 
 # Action unrecognised ------------------------------------
 else
